In [352]:
import pandas as pd
import numpy as np
import sympy as sy
from scipy import integrate
from sympy import oo
import math as mt
from numpy import linalg

### Examen número 2: Métodos computacionales 
A) Para aproximar el valor de la integral se toma las singularidades del integrando, como n = 4 se sustituye el valor
$$ \int_{0}^{\infty}\sin(x^4)dx = \int_{0}^{1}\sin(x^4) dx + \int_{1}^{\infty}\sin(x^4) dx$$, la primer a integral se resuelve sin ningún inconveniente. 

Para resolver la segunda integral se quita la singularidad a derecha, cambiando a $x = \frac{1}{t^{1/4}}$ se deriva y se obtiene $dx = \frac{-1}{4} t^{-3/4} dt$, reemplazando en la integral se llega a que $$ \frac{1}{4} \int_{0}^{1} t^{-3/4} \sin(\frac{1}{t}) dx $$ 

Como ya se tiene una singularidad a izquierda se puede aproximar el integrando y así hallar el valor aproximado:


In [ ]:
#1. Número entero aleatorio
np.random.seed(1017246860)
n = np.random.randint(2,20)
print("El número aleatorio con el número de cédula es ",n)

In [ ]:
#Solución por medio de sympy para validar el resultado
x = sy.symbols("x") #Construye la variable independiente
#Integrando
def sin_(x,n):
    """
    x = variable independiente
    n = potencia de x
    """
    s = sy.sin(x**n)
    return s
#Integración de la expresión en forma simbolica 
int1 = sy.integrate(sin_(x,n),(x,0,oo))
print(f"El valor con dos cifras significativas de la integral con sympy es {int1.n():.2}")

In [ ]:
#2. Hallar el valor de la integral con integrate.quad
#Se define la primera integral
def sin_(t):
    s = np.sin(t**4)
    return s
integral = integrate.quad(sin_,0,1)
#============================================================================
def sin1(t):
    s = ((1/t)-(1/mt.factorial(3))*(1/t**3)) * (t**(-3/4))* 1/4
    return s
#Primera integral que corresponde al poliniomio de grado 4 de taylor
# De la función sin(1/t)
integral1 = integrate.quad(sin1,0,1)

#============================================================================
def sin2(t):
    s = (np.sin(1/t)-((1/t)-(1/mt.factorial(3))*(1/t**3)) ) * (t**(-3/4))* 1/4
    return s
integral2 = integrate.quad(sin2,0,1)
#EL valor de la integral es la suma de la integral + integral2
inte = integral[0]+integral1[0] + integral2[0]

In [ ]:
print(f"El valor de la integral con dos cifras significativas es {inte:.2}")

B)

In [230]:
url = "https://raw.githubusercontent.com/ComputationalMethods/Evaluacion_2022-1/main/data/lista_pares.json"
df = pd.read_json(url)
df1 = df.iloc[[6,0]]
df1

lista  \
6  [1, -3, -4, -5, 6, 6, 8, -9]   
0   [1, 1, 2, 3, -4, -4, -5, 6]   

                                               pares  
6  {'S': 3, 'ψ': [[-3, 6], [-5, 8], [1, -4], [6, ...  
0  {'S': 2, 'ψ': [[3, -5], [2, -4], [-4, 6], [1, ...

In [231]:
df2 = df1["pares"][6]
df3 = df1["pares"][0]

In [232]:
df2["ψ"]
df3["ψ"]

[[3, -5], [2, -4], [-4, 6], [1, 1], [-5, 3], [-4, 2], [6, -4]]

In [325]:
a = []
b = []
for i in df2["ψ"]:
    for k in i:
        a.append(k)

for i in df3["ψ"]:
    for k in i:
        b.append(k)
        

e = df1["lista"][0]
f = df1["lista"][6]
c = [df3["S"],df2["S"]]
c1 = b.extend(c)
print(b)
print(e)
print(f)
print(a)
r1 = np.reshape(b,(2,8))
r2= np.reshape(a,(2,8))
filas = 8
columna = 8 
A = np.zeros([filas,columna])
B1 = np.array([r1[0],r1[1],r2[0],r2[1],f,e])

[3, -5, 2, -4, -4, 6, 1, 1, -5, 3, -4, 2, 6, -4, 2, 3]
[1, 1, 2, 3, -4, -4, -5, 6]
[1, -3, -4, -5, 6, 6, 8, -9]
[-3, 6, -5, 8, 1, -4, 6, -9, 6, -3, 8, -5, -4, 1, -9, 6]


In [283]:
f = 8
c = 8
B = np.array([[0 for x in range(c)] for y in range(f)])
for i in range(1,f):
    for j in range(1,c):
        B[i][j] = (i+1)*(j+1)

In [341]:
f = 8
c = 8
B = np.zeros((f,c))
for i in range(1,f):
    for j in range(1,c):
        B[i][j] = (i+1)*(j+1)

In [359]:
L = np.zeros((8,8))
for i in range(1,len(B1)):
    for k in B1[i]:
        L[i] = k

In [361]:
L

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [-9., -9., -9., -9., -9., -9., -9., -9.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [-9., -9., -9., -9., -9., -9., -9., -9.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [363]:
#Determinante
linalg.det(L)
print("El determinante es igual a cero ")

El determinante es igual a cero 


In [364]:
#Autovalores 
autovectores, autovalores = linalg.eig(L)

In [366]:
#Autovalores
autovalores

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5771294 ,  0.        ,  0.        ],
       [ 0.19245009,  0.29140358, -0.06441774, -0.54920265,  0.06441774,
        -0.07470565, -0.07470565, -0.07470565],
       [-0.57735027, -0.54541234, -0.44094427, -0.20151712,  0.44094427,
        -0.51136583, -0.51136583, -0.51136583],
       [ 0.38490018,  0.41699741,  0.19098398,  0.76228327, -0.19098398,
         0.22148532,  0.22148532,  0.22148532],
       [-0.57735027, -0.54541234, -0.44094427, -0.20151712,  0.44094427,
        -0.51136583, -0.51136583, -0.51136583],
       [ 0.38490018,  0.38242369,  0.7553223 ,  0.18995362, -0.7553223 ,
         0.29882261,  0.29882261,  0.29882261],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.5771294 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.5771294 ]])

In [367]:
#Autovectores
autovectores

array([-3.0000000e+00,  1.3723028e-14,  0.0000000e+00, -8.8817842e-16,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00])